"""The built-in example pages behind "Try example" in the four web monitoring tools.

Generated by tests/fixtures/examples/build_pages.py; do not edit by hand. Each
page is copied byte for byte from a golden pair (named below) whose expected
changes are written down and checked by the golden suite, so every example
shows a verified comparison. tests/test_examples.py fails if a copy here
drifts from its golden pair.
"""

# ruff: noqa: E501

from __future__ import annotations

PAGES: dict[str, dict[str, str]] = {
    "web": {
        "pair": "web-pairs/combined-update",
        "url": "https://example.com/agreement",
        "before": """<!doctype html><html lang="en"><head>
<title>Service Agreement | Example</title>
<meta name="description" content="The standard terms for professional services.">
<link rel="canonical" href="https://example.com/agreement">
</head><body>
<nav class="navbar"><a href="/">Home</a><a href="/pricing">Pricing</a></nav>
<main>
<h1>Service Agreement</h1>
<p>This agreement sets out the terms under which services are provided.</p>
<h2>Pricing</h2>
<p>The standard plan costs 50,000 per year for each licence purchased.</p>
<p>Volume discounts of 10% apply to orders above one hundred licences.</p>

<h2>Delivery</h2>
<p>Delivery is scheduled for 30 June 2026 at the agreed location.</p>
<ul>
<li>Reports are delivered monthly</li>
<li>Support is included for twelve months</li>
</ul>

<h2>Resources</h2>
<p>See the <a href="https://example.com/guide">implementation guide</a> for further detail.</p>
<table><thead><tr><th>Plan</th><th>Price</th><th>Users</th></tr></thead><tbody>
<tr><td>Standard</td><td>50,000</td><td>25</td></tr>
<tr><td>Premium</td><td>90,000</td><td>100</td></tr>
</tbody></table>

</main>
<footer class="site-footer"><p>Copyright 2026 Example Ltd</p></footer>
</body></html>
""",
        "after": """<!doctype html><html lang="en"><head>
<title>Service Agreement (2026 revision) | Example</title>
<meta name="description" content="The standard terms for professional services.">
<link rel="canonical" href="https://example.com/agreement">
</head><body>
<nav class="navbar"><a href="/">Home</a><a href="/pricing">Pricing</a></nav>
<main>
<h1>Service Agreement</h1>
<p>This agreement sets out the terms under which services are provided.</p>
<h2>Pricing</h2>
<p>The standard plan costs 75,000 per year for each licence purchased.</p>
<p>Volume discounts of 10% apply to orders above one hundred licences.</p>

<h2>Delivery</h2>
<p>Delivery is scheduled for 15 July 2026 at the agreed location.</p>
<ul>
<li>Reports are delivered monthly</li>
<li>Support is included for twelve months</li>
</ul>

<h2>Resources</h2>
<p>See the <a href="https://example.com/guide">implementation guide</a> for further detail.</p>
<table><thead><tr><th>Plan</th><th>Price</th><th>Users</th></tr></thead><tbody>
<tr><td>Standard</td><td>50,000</td><td>25</td></tr>
<tr><td>Premium</td><td>95,000</td><td>100</td></tr>
</tbody></table>
<h2>Termination</h2><p>Either party may terminate with sixty days notice.</p>
</main>
<footer class="site-footer"><p>Copyright 2026 Example Ltd</p></footer>
</body></html>
""",
    },
    "policy": {
        "pair": "policy-pairs/terms-revision",
        "url": "https://example.com/terms",
        "before": """<!doctype html><html lang="en"><head>
<title>Terms of Service | Northwind</title>
<meta name="description" content="Terms of service for Northwind Software Limited.">
</head><body>
<nav class="navbar"><a href="/">Home</a><a href="/pricing">Pricing</a><a href="/terms">Terms</a></nav>
<main>
<h1>Terms of Service</h1>
<p class="updated">Last updated: 12 March 2026</p>
<p>These terms govern your use of the Northwind platform. By creating an account you
agree to them.</p>

<h2>Fees and charges</h2>
<p>The standard plan costs 480 per user per year, charged annually in advance.
We may change our pricing on 30 days notice before your renewal date.</p>

<h2>Payment terms</h2>
<p>Invoices are payable within 30 days of issue. Late payment may result in
suspension of the service until the overdue amount is settled.</p>

<h2>Refunds</h2>
<p>Our refund policy allows a full refund if you cancel within 14 days of your
first payment. After that period fees are non-refundable.</p>

<h2>Cancellation and termination</h2>
<p>You may cancel your subscription at any time by giving 30 days written
notice. We may terminate this agreement if you materially breach these terms.</p>

<h2>Automatic renewal</h2>
<p>Your subscription renews automatically for a further twelve months unless you cancel before the renewal date.</p>

<h2>Limitation of liability</h2>
<p>Our total liability under this agreement shall not exceed 10,000 or the fees paid in
the preceding twelve months, whichever is lower.</p>

<h2>Warranties</h2>
<p>The service is provided as is, without warranties of any kind. We disclaim all implied warranties including fitness for a particular purpose.</p>

<h2>Licence and ownership</h2>
<p>You grant us a non-exclusive licence to host and process your content solely to
provide the service. All intellectual property rights in the platform remain ours.</p>

<h2>Acceptable use</h2>
<p>Prohibited conduct includes scraping the service, reselling access without our
consent. We may suspend your account for breach of these terms.</p>

<h2>Governing law</h2>
<p>This agreement is governed by the laws of England and Wales and the courts of
England and Wales shall have exclusive jurisdiction.</p>

<h2>Disputes</h2>
<p>Any dispute arising under these terms shall be resolved by binding arbitration in London.</p>

<h2>About Northwind</h2>
<p>Northwind Software Limited was founded in 2011 and employs 400 people across
three offices. Our support team is available on weekdays.</p>
</main>
<footer class="site-footer"><p>Copyright 2026 Northwind Software Limited</p></footer>
</body></html>
""",
        "after": """<!doctype html><html lang="en"><head>
<title>Terms of Service | Northwind</title>
<meta name="description" content="Terms of service for Northwind Software Limited.">
</head><body>
<nav class="navbar"><a href="/">Home</a><a href="/pricing">Pricing</a><a href="/terms">Terms</a></nav>
<main>
<h1>Terms of Service</h1>
<p class="updated">Last updated: 1 September 2026</p>
<p>These terms govern your use of the Northwind platform. By creating an account you
agree to them.</p>

<h2>Fees and charges</h2>
<p>The standard plan costs 480 per user per year, charged annually in advance.
We may change our pricing on 30 days notice before your renewal date.</p>

<h2>Payment terms</h2>
<p>Invoices are payable within 30 days of issue. Late payment may result in
suspension of the service until the overdue amount is settled.</p>

<h2>Refunds</h2>
<p>Our refund policy allows a full refund if you cancel within 7 days of your
first payment. After that period fees are non-refundable.</p>

<h2>Cancellation and termination</h2>
<p>You may cancel your subscription at any time by giving 60 days written
notice. We may terminate this agreement if you materially breach these terms.</p>

<h2>Automatic renewal</h2>
<p>Your subscription renews automatically for a further twelve months unless you cancel before the renewal date.</p>

<h2>Limitation of liability</h2>
<p>Our total liability under this agreement shall not exceed 10,000 or the fees paid in
the preceding twelve months, whichever is lower.</p>

<h2>Warranties</h2>
<p>The service is provided as is, without warranties of any kind. We disclaim all implied warranties including fitness for a particular purpose.</p>

<h2>Licence and ownership</h2>
<p>You grant us a non-exclusive licence to host and process your content solely to
provide the service. All intellectual property rights in the platform remain ours.</p>

<h2>Acceptable use</h2>
<p>Prohibited conduct includes scraping the service, reselling access without our
consent. We may suspend your account for breach of these terms.</p>

<h2>Governing law</h2>
<p>This agreement is governed by the laws of Ireland and the courts of
Ireland shall have exclusive jurisdiction.</p>

<h2>Disputes</h2>
<p>Any dispute arising under these terms shall be resolved by binding arbitration in London.</p>

<h2>Service levels</h2>
<p>We aim for 99.9% availability measured monthly. Credits are the sole remedy for downtime.</p>

<h2>About Northwind</h2>
<p>Northwind Software Limited was founded in 2011 and employs 400 people across
three offices. Our support team is available on weekdays.</p>
</main>
<footer class="site-footer"><p>Copyright 2026 Northwind Software Limited</p></footer>
</body></html>
""",
    },
    "competitor": {
        "pair": "competitor-pairs/mixed-release",
        "url": "https://competitor.example.com/pricing",
        "before": """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Pricing — Northwind Task Management</title>
<meta name="description" content="Simple per-user pricing for teams of every size. Start free for 14 days.">
<link rel="canonical" href="https://competitor.example.com/pricing">
</head>
<body>
<header class="site-header">
  <nav aria-label="Main">
    <a href="https://competitor.example.com/">Northwind</a>
    <a href="https://competitor.example.com/product">Product</a>
    <a href="https://competitor.example.com/pricing">Pricing</a>
    <a href="https://competitor.example.com/login">Log in</a>
  </nav>
</header>
<main>
  <section class="hero">
    <h1>Task management that keeps every team moving</h1>
    <p>Plan projects, track work and hit deadlines together, in one shared workspace.</p>
    <p class="actions"><a class="button primary" href="https://competitor.example.com/signup">Start free trial</a> <a class="button" href="https://competitor.example.com/demo">Book a demo</a></p>
  </section>

  <section class="plans">
    <h2>Plans</h2>
    <p>Every plan includes unlimited guests and a 99.9% uptime commitment.</p>
    <div class="plan">
      <h3>Starter</h3>
      <p class="price">$8 per user per month, billed annually</p>
      <ul>
        <li>Up to 3 projects</li>
        <li>Basic reporting</li>
        <li>Email support</li>
      </ul>
      <p><a class="button" href="https://competitor.example.com/signup?plan=starter">Choose Starter</a></p>
    </div>
    <div class="plan">
      <h3>Team</h3>
      <p class="price">$15 per user per month, billed annually</p>
      <ul>
        <li>Unlimited projects</li>
        <li>Timeline view</li>
        <li>Priority email support</li>
      </ul>
      <p><a class="button" href="https://competitor.example.com/signup?plan=team">Choose Team</a></p>
    </div>
    <div class="plan">
      <h3>Business</h3>
      <p class="price">$29 per user per month, billed annually</p>
      <ul>
        <li>Everything in Team</li>
        <li>Audit log</li>
        <li>Single sign-on</li>
      </ul>
      <p><a class="button" href="https://competitor.example.com/signup?plan=business">Choose Business</a></p>
    </div>
  </section>

  <section class="compare">
    <h2>Compare plans</h2>
    <table>
      <tr><th>Included</th><th>Starter</th><th>Team</th><th>Business</th></tr>
      <tr><td>Projects</td><td>3</td><td>Unlimited</td><td>Unlimited</td></tr>
      <tr><td>Storage</td><td>5 GB</td><td>100 GB</td><td>1 TB</td></tr>
      <tr><td>Audit log</td><td>No</td><td>No</td><td>Yes</td></tr>
    </table>
  </section>

  <section class="features">
    <h2>Features</h2>
    <ul>
      <li>Kanban boards</li>
      <li>Gantt timelines</li>
      <li>Recurring tasks</li>
      <li>Time tracking reports</li>
    </ul>
  </section>

  <section class="faq">
    <h2>Frequently asked questions</h2>
    <h3>Can I change plans later?</h3>
    <p>Yes. You can upgrade or downgrade at any time from your account settings.</p>
    <h3>Do you offer discounts for nonprofits?</h3>
    <p>Registered nonprofits receive 30% off any annual plan.</p>
  </section>

  <section class="about">
    <h2>About Northwind</h2>
    <p>Northwind was founded in 2016 and now serves more than 12,000 teams in 40 countries.</p>
    <p>Read the <a href="https://competitor.example.com/blog">Northwind blog</a> for product news and customer stories.</p>
  </section>
</main>
<footer class="site-footer">
  <p>© 2026 Northwind Software Ltd. All rights reserved.</p>
  <a href="https://competitor.example.com/privacy">Privacy</a>
  <a href="https://competitor.example.com/terms">Terms</a>
</footer>
</body>
</html>
""",
        "after": """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Pricing — Northwind Task Management with Automations</title>
<meta name="description" content="Simple per-user pricing for teams of every size. Start free for 14 days.">
<link rel="canonical" href="https://competitor.example.com/pricing">
</head>
<body>
<header class="site-header">
  <nav aria-label="Main">
    <a href="https://competitor.example.com/">Northwind</a>
    <a href="https://competitor.example.com/product">Product</a>
    <a href="https://competitor.example.com/pricing">Pricing</a>
    <a href="https://competitor.example.com/login">Log in</a>
  </nav>
</header>
<main>
  <section class="hero">
    <h1>Task management with automations built in</h1>
    <p>Plan projects, track work and hit deadlines together, in one shared workspace.</p>
    <p class="actions"><a class="button primary" href="https://competitor.example.com/signup">Try Northwind free</a> <a class="button" href="https://competitor.example.com/demo">Book a demo</a></p>
  </section>

  <section class="plans">
    <h2>Plans</h2>
    <p>Every plan includes unlimited guests and a 99.9% uptime commitment.</p>
    <div class="plan">
      <h3>Starter</h3>
      <p class="price">$8 per user per month, billed annually</p>
      <ul>
        <li>Up to 3 projects</li>
        <li>Basic reporting</li>
        <li>Email support</li>
      </ul>
      <p><a class="button" href="https://competitor.example.com/signup?plan=starter">Choose Starter</a></p>
    </div>
    <div class="plan">
      <h3>Team</h3>
      <p class="price">$16 per user per month, billed annually</p>
      <ul>
        <li>Unlimited projects</li>
        <li>Timeline view</li>
        <li>Priority email support</li>
        <li>Automations</li>
      </ul>
      <p><a class="button" href="https://competitor.example.com/signup?plan=team">Choose Team</a></p>
    </div>
    <div class="plan">
      <h3>Business</h3>
      <p class="price">$29 per user per month, billed annually</p>
      <ul>
        <li>Everything in Team</li>
        <li>Audit log</li>
        <li>Single sign-on</li>
      </ul>
      <p><a class="button" href="https://competitor.example.com/signup?plan=business">Choose Business</a></p>
    </div>
  </section>

  <section class="compare">
    <h2>Compare plans</h2>
    <table>
      <tr><th>Included</th><th>Starter</th><th>Team</th><th>Business</th></tr>
      <tr><td>Projects</td><td>3</td><td>Unlimited</td><td>Unlimited</td></tr>
      <tr><td>Storage</td><td>5 GB</td><td>100 GB</td><td>1 TB</td></tr>
      <tr><td>Audit log</td><td>No</td><td>No</td><td>Yes</td></tr>
    </table>
  </section>

  <section class="features">
    <h2>Features</h2>
    <ul>
      <li>Kanban boards</li>
      <li>Gantt timelines</li>
      <li>Recurring tasks</li>
      <li>Time tracking reports</li>
      <li>Automations</li>
    </ul>
  </section>

  <section class="faq">
    <h2>Frequently asked questions</h2>
    <h3>Can I change plans later?</h3>
    <p>Yes. You can upgrade or downgrade at any time from your account settings.</p>
    <h3>Do you offer discounts for nonprofits?</h3>
    <p>Registered nonprofits receive 30% off any annual plan.</p>
  </section>

  <section class="about">
    <h2>About Northwind</h2>
    <p>Northwind was founded in 2016 and now serves more than 13,000 teams in 40 countries.</p>
    <p>Read the <a href="https://competitor.example.com/blog">Northwind blog</a> for product news and customer stories.</p>
  </section>
</main>
<footer class="site-footer">
  <p>© 2026 Northwind Software Ltd. All rights reserved.</p>
  <a href="https://competitor.example.com/privacy">Privacy</a>
  <a href="https://competitor.example.com/terms">Terms</a>
</footer>
</body>
</html>
""",
    },
    "price": {
        "pair": "price-pairs/mixed-release",
        "url": "https://tasklane.example.com/pricing",
        "before": """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Pricing — Tasklane</title>
<meta name="description" content="Simple per-user pricing for Tasklane, the project planner for small teams.">
<link rel="canonical" href="https://tasklane.example.com/pricing">
</head>
<body>
<header class="site-header">
  <nav aria-label="Main">
    <a href="https://tasklane.example.com/">Tasklane</a>
    <a href="https://tasklane.example.com/features">Features</a>
    <a href="https://tasklane.example.com/pricing">Pricing</a>
    <a href="https://tasklane.example.com/login">Log in</a>
  </nav>
</header>
<main>
  <section class="hero">
    <h1>Tasklane pricing</h1>
    <p>Pick the plan that fits your team. You can change plans at any time.</p>
    <p class="note">All prices in USD.</p>
  </section>

  <section class="plans">
    <h2>Plans</h2>
    <div class="plan">
      <h3>Starter</h3>
      <p class="price">$8 per user per month</p>
      <ul>
        <li>Up to 10 users</li>
        <li>14-day free trial</li>
        <li>Email support</li>
      </ul>
      <p><a class="button" href="https://tasklane.example.com/signup?plan=starter">Start free trial</a></p>
    </div>
    <div class="plan">
      <h3>Team plan</h3>
      <p class="price">$15 per user per month, billed annually</p>
      <p class="promo">Was $24, now $19 for the first year</p>
      <ul>
        <li>Unlimited projects</li>
        <li>Timeline view</li>
      </ul>
      <p><a class="button" href="https://tasklane.example.com/signup?plan=team">Start free trial</a></p>
    </div>
    <div class="plan">
      <h3>Business</h3>
      <p class="price">$24 per user per month</p>
      <p class="status">Status: Available</p>
      <ul>
        <li>Single sign-on</li>
        <li>Audit log</li>
      </ul>
    </div>

  </section>

  <section class="compare">
    <h2>Compare plans</h2>
    <table>
      <tr><th>Plan</th><th>Price per user (USD)</th><th>Storage</th></tr>
      <tr><td>Starter</td><td>8</td><td>5 GB</td></tr>
      <tr><td>Business</td><td>24</td><td>1 TB</td></tr>
    </table>
  </section>

  <section class="faq">
    <h2>Frequently asked questions</h2>
    <h3>Can I cancel?</h3>
    <p>Yes. You can cancel at any time from your account settings.</p>
  </section>

  <section class="about">
    <h2>About Tasklane</h2>
    <p>Tasklane serves more than 12,000 teams with 99.9% uptime.</p>
    <p>Read the <a href="https://tasklane.example.com/blog">Tasklane blog</a> for product news.</p>

  </section>
</main>
<footer class="site-footer">
  <p>© 2026 Tasklane Ltd. All rights reserved.</p>
  <a href="https://tasklane.example.com/privacy">Privacy</a>
  <a href="https://tasklane.example.com/terms">Terms</a>
</footer>
</body>
</html>
""",
        "after": """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Pricing — Tasklane</title>
<meta name="description" content="Simple per-user pricing for Tasklane, the project planner for small teams.">
<link rel="canonical" href="https://tasklane.example.com/pricing">
</head>
<body>
<header class="site-header">
  <nav aria-label="Main">
    <a href="https://tasklane.example.com/">Tasklane</a>
    <a href="https://tasklane.example.com/features">Features</a>
    <a href="https://tasklane.example.com/pricing">Pricing</a>
    <a href="https://tasklane.example.com/login">Log in</a>
  </nav>
</header>
<main>
  <section class="hero">
    <h1>Tasklane pricing</h1>
    <p>Pick the plan that fits your team. You can change plans at any time.</p>
    <p class="note">All prices in USD.</p>
  </section>

  <section class="plans">
    <h2>Plans</h2>
    <div class="plan">
      <h3>Starter</h3>
      <p class="price">$8 per user per month</p>
      <ul>
        <li>Up to 15 users</li>
        <li>14-day free trial</li>
        <li>Email support</li>
      </ul>
      <p><a class="button" href="https://tasklane.example.com/signup?plan=starter">Start free trial</a></p>
    </div>
    <div class="plan">
      <h3>Growth plan</h3>
      <p class="price">$18 per user per month, billed annually</p>
      <p class="promo">Was $24, now $16 for the first year</p>
      <ul>
        <li>Unlimited projects</li>
        <li>Timeline view</li>
      </ul>
      <p><a class="button" href="https://tasklane.example.com/signup?plan=team">Start free trial</a></p>
    </div>
    <div class="plan">
      <h3>Business</h3>
      <p class="price">$24 per user per month</p>
      <p class="status">Status: Contact sales</p>
      <ul>
        <li>Single sign-on</li>
        <li>Audit log</li>
      </ul>
    </div>

  </section>

  <section class="compare">
    <h2>Compare plans</h2>
    <table>
      <tr><th>Plan</th><th>Price per user (USD)</th><th>Storage</th></tr>
      <tr><td>Starter</td><td>8</td><td>5 GB</td></tr>
      <tr><td>Business</td><td>24</td><td>1 TB</td></tr>
    </table>
  </section>

  <section class="faq">
    <h2>Frequently asked questions</h2>
    <h3>Can I cancel?</h3>
    <p>Yes. You can cancel at any time from your account settings.</p>
  </section>

  <section class="about">
    <h2>About Tasklane</h2>
    <p>Tasklane serves more than 13,000 teams with 99.9% uptime.</p>
    <p>Read the <a href="https://tasklane.example.com/news">Tasklane blog</a> for product news.</p>

  </section>
</main>
<footer class="site-footer">
  <p>© 2026 Tasklane Ltd. All rights reserved.</p>
  <a href="https://tasklane.example.com/privacy">Privacy</a>
  <a href="https://tasklane.example.com/terms">Terms</a>
</footer>
</body>
</html>
""",
    },
}
