/**
 * Integration test for the browser-side PDF reader, run against the real PDFs
 * generated by the engine's golden suite.
 *
 * The unit tests cover our own logic; this covers the part we don't control —
 * that PDF.js actually opens these files, reports the right page count, and
 * fails in the ways we translate into user-facing messages.
 *
 * Run `diffnexa golden generate` (from the repository root) first. CI does this
 * automatically before running the web tests.
 */

import { execFileSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

import { beforeAll, describe, expect, it } from "vitest";

import { classifyPdfJsError } from "@/lib/pdf-preview";

const REPO_ROOT = join(import.meta.dirname, "..", "..", "..");
const PAIRS = join(REPO_ROOT, "golden", ".generated", "synthetic");
const available = existsSync(PAIRS);

type PdfJs = typeof import("pdfjs-dist/legacy/build/pdf.mjs");
let pdfjs: PdfJs;

function pairFile(pair: string, side: "old" | "new"): Uint8Array {
  return new Uint8Array(readFileSync(join(PAIRS, pair, `${side}.pdf`)));
}

async function pageCount(data: Uint8Array): Promise<number> {
  const task = pdfjs.getDocument({
    data,
    disableAutoFetch: true,
    disableStream: true,
    enableXfa: false,
  });
  const document = await task.promise;
  const pages = document.numPages;
  await task.destroy();
  return pages;
}

describe.skipIf(!available)("reading real PDFs with PDF.js", () => {
  beforeAll(async () => {
    pdfjs = await import("pdfjs-dist/legacy/build/pdf.mjs");
    pdfjs.GlobalWorkerOptions.workerSrc = join(
      REPO_ROOT,
      "apps",
      "web",
      "node_modules",
      "pdfjs-dist",
      "legacy",
      "build",
      "pdf.worker.min.mjs",
    );
  });

  it("counts pages in an ordinary document", async () => {
    await expect(pageCount(pairFile("vacancy-number-change", "old"))).resolves.toBe(3);
  });

  it("counts pages after a page was inserted", async () => {
    await expect(pageCount(pairFile("inserted-page", "new"))).resolves.toBe(4);
  });

  it("reads a document with a rotated page", async () => {
    await expect(pageCount(pairFile("rotated-page", "old"))).resolves.toBe(3);
  });

  it("reads a document containing a scanned page", async () => {
    await expect(pageCount(pairFile("scanned-page", "new"))).resolves.toBe(3);
  });

  it("rejects a damaged file in a way we can explain", async () => {
    const whole = pairFile("identical-notice", "old");
    const truncated = whole.slice(0, Math.floor(whole.length / 3));
    try {
      await pageCount(truncated);
      throw new Error("a truncated PDF should not open");
    } catch (error) {
      expect(classifyPdfJsError(error)).toBe("corrupted");
    }
  });

  it("rejects a file that is not a PDF at all", async () => {
    try {
      await pageCount(new TextEncoder().encode("GIF89a definitely not a pdf"));
      throw new Error("a non-PDF should not open");
    } catch (error) {
      expect(classifyPdfJsError(error)).toBe("corrupted");
    }
  });
});

describe("password-protected PDFs", () => {
  it("is reported as needing a password, not as a crash", async () => {
    const passwordError = Object.assign(new Error("No password given"), {
      name: "PasswordException",
    });
    expect(classifyPdfJsError(passwordError)).toBe("password_protected");
  });
});

describe.skipIf(!available)("the golden pairs are present", () => {
  it("were generated by the engine", () => {
    const listed = execFileSync("ls", [PAIRS], { encoding: "utf8" }).split("\n").filter(Boolean);
    expect(listed).toContain("inserted-page");
    expect(listed.length).toBeGreaterThanOrEqual(10);
  });
});
