"""Writes diffnexa_engine/examples/pages.py from the golden pairs behind each web example.

Run from apps/engine after changing an example pair:

    python tests/fixtures/examples/build_pages.py

The pages are embedded as Python strings, rather than shipped as data files, so
they are part of the engine however it is installed. tests/test_examples.py
fails if the copy and its golden pair ever differ.
"""

from __future__ import annotations

from pathlib import Path

REPO = Path(__file__).resolve().parents[5]
GOLDEN = REPO / "golden"
TARGET = REPO / "apps" / "engine" / "diffnexa_engine" / "examples" / "pages.py"

#: tool -> (golden pair, the address the example page stands for)
EXAMPLES = {
    "web": ("web-pairs/combined-update", "https://example.com/agreement"),
    "policy": ("policy-pairs/terms-revision", "https://example.com/terms"),
    "competitor": ("competitor-pairs/mixed-release", "https://competitor.example.com/pricing"),
    "price": ("price-pairs/mixed-release", "https://tasklane.example.com/pricing"),
}

HEADER = '''"""The built-in example pages behind "Try example" in the four web monitoring tools.

Generated by tests/fixtures/examples/build_pages.py; do not edit by hand. Each
page is copied byte for byte from a golden pair (named below) whose expected
changes are written down and checked by the golden suite, so every example
shows a verified comparison. tests/test_examples.py fails if a copy here
drifts from its golden pair.
"""

# ruff: noqa: E501

from __future__ import annotations

PAGES: dict[str, dict[str, str]] = {'''


def main() -> None:
    lines = [HEADER]
    for tool, (pair, url) in EXAMPLES.items():
        before = (GOLDEN / pair / "before.html").read_text(encoding="utf-8")
        after = (GOLDEN / pair / "after.html").read_text(encoding="utf-8")
        for text in (before, after):
            if '"""' in text or "\\" in text:
                raise SystemExit(f"{pair}: cannot be embedded as a plain triple-quoted string")
        lines += [
            f'    "{tool}": {{',
            f'        "pair": "{pair}",',
            f'        "url": "{url}",',
            f'        "before": """{before}""",',
            f'        "after": """{after}""",',
            "    },",
        ]
    lines.append("}")
    TARGET.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {TARGET}")


if __name__ == "__main__":
    main()
